title: 技术笔记博客
description: 技术笔记分享
baseurl: "/DrillDown.github.io"
url: "https://manredeshanxiren.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 插件
gems:
  - jekyll-feed
  - jekyll-sitemap

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# 默认值
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "manredeshanxiren"

# 布局目录
layout_dir: layouts

# 数据目录
data_dir: data

# 包含目录
include:
  - .github

# 分类
collections:
  notes:
    output: true
    permalink: /notes/:title/
    title: 技术笔记

# notes列表页面
notes:
  permalink: /notes/